export const countries = [
  { flag: "🇦🇹", name: "Austria", capital: "Viena" },
  { flag: "🇧🇪", name: "Bélgica", capital: "Bruselas" },
  { flag: "🇧🇬", name: "Bulgaria", capital: "Sofía" },
  { flag: "🇭🇷", name: "Croacia", capital: "Zagreb" },
  { flag: "🇨🇾", name: "Chipre", capital: "Nicosia" },
  { flag: "🇨🇿", name: "República Checa", capital: "Praga" },
  { flag: "🇩🇰", name: "Dinamarca", capital: "Copenhague" },
  { flag: "🇪🇪", name: "Estonia", capital: "Tallin" },
  { flag: "🇫🇮", name: "Finlandia", capital: "Helsinki" },
  { flag: "🇫🇷", name: "Francia", capital: "París" },
  { flag: "🇩🇪", name: "Alemania", capital: "Berlín" },
  { flag: "🇬🇷", name: "Grecia", capital: "Atenas" },
  { flag: "🇭🇺", name: "Hungría", capital: "Budapest" },
  { flag: "🇮🇪", name: "Irlanda", capital: "Dublín" },
  { flag: "🇮🇹", name: "Italia", capital: "Roma" },
  { flag: "🇱🇻", name: "Letonia", capital: "Riga" },
  { flag: "🇱🇹", name: "Lituania", capital: "Vilna" },
  { flag: "🇱🇺", name: "Luxemburgo", capital: "Luxemburgo" },
  { flag: "🇲🇹", name: "Malta", capital: "La Valeta" },
  { flag: "🇳🇱", name: "Países Bajos", capital: "Ámsterdam" },
  { flag: "🇵🇱", name: "Polonia", capital: "Varsovia" },
  { flag: "🇵🇹", name: "Portugal", capital: "Lisboa" },
  { flag: "🇷🇴", name: "Rumanía", capital: "Bucarest" },
  { flag: "🇸🇰", name: "Eslovaquia", capital: "Bratislava" },
  { flag: "🇸🇮", name: "Eslovenia", capital: "Liubliana" },
  { flag: "🇪🇸", name: "España", capital: "Madrid" },
  { flag: "🇸🇪", name: "Suecia", capital: "Estocolmo" },
];
